<?php
/**
 * @file
 * Adds permissions for clearing Drupal cache.
 * Sites might slow down while cache rebuilds.
 * Will not clear web browser cache :p.
 * Adds a menu link titled "Clear Cache" on administrative tool-bar.
 */

/**
 * Implements hook_permission().
 */
function clear_cache_permission() {
  return array(
    'use clear cache' => array(
      'title' => t('Can clear cache'),
    ),
  );
}

/**
 * Implement hook_menu().
 */
function clear_cache_menu() {
  $items = array();
  $items['admin/clearcache'] = array(
    'title' => 'Clear Cache',
    'page callback' => 'clear_cache_action',
    'access arguments' => array('use clear cache'),
    'type' => MENU_NORMAL_ITEM,
    'weight' => 16,
  );
  return $items;
}

/**
 * Flush all drupal cache, redirect to homepage.
 */
function clear_cache_action() {
  drupal_flush_all_caches();
  drupal_set_message($message = t('Success! All Drupal Caches cleared.'), $type = 'status');
  drupal_goto();
}
